/**
 * @file index.jsx
 * @description Radio sample section.
 */

'use strict';
import { FlexibleSection } from '../../Content/components/GridSection';
import Radio from '../../Radio';

import * as styles from './RadioSampleSection.module.css';

/**
 * Radio sample section.
 * @returns Returns the component.
 */
function RadioSampleSection() {
    return (
        <FlexibleSection
            style={{
                display: 'flex',
                flexFlow: 'columm nowrap',
                justifyContent: 'center',
                alignItems: 'center',
                padding: '50px 20px',
                textAlign: 'center',
            }}
        >
            <div className={styles['content']}>
                <h1>Default Radios</h1>
                <Radio labelText="Primary" id="r-1" name="rg-1" value="r1" />
                <Radio
                    labelText="Red"
                    color="red"
                    id="r-2"
                    name="rg-1"
                    value="r2"
                />
                <Radio
                    labelText="Orange"
                    color="orange"
                    id="r-3"
                    name="rg-1"
                    value="r3"
                />
                <Radio
                    labelText="Yellow"
                    color="yellow"
                    id="r-4"
                    name="rg-1"
                    value="r4"
                />
                <Radio
                    labelText="Green"
                    color="green"
                    id="r-5"
                    name="rg-1"
                    value="r5"
                />
                <Radio
                    labelText="Blue"
                    color="blue"
                    id="r-6"
                    name="rg-1"
                    value="r6"
                />
                <Radio
                    labelText="Purple"
                    color="purple"
                    id="r-7"
                    name="rg-1"
                    value="r7"
                />
                <h1 style={{ marginTop: '26px' }}>Alternative Radios 1</h1>
                <Radio
                    labelText="Primary"
                    altStyle="alt-1"
                    id="ra-1"
                    name="rg-2"
                    value="ra1"
                />
                <Radio
                    labelText="Red"
                    color="red"
                    altStyle="alt-1"
                    id="ra-2"
                    name="rg-2"
                    value="ra2"
                />
                <Radio
                    labelText="Orange"
                    color="orange"
                    altStyle="alt-1"
                    id="ra-3"
                    name="rg-2"
                    value="ra3"
                />
                <Radio
                    labelText="Yellow"
                    color="yellow"
                    altStyle="alt-1"
                    id="ra-4"
                    name="rg-2"
                    value="ra4"
                />
                <Radio
                    labelText="Green"
                    color="green"
                    altStyle="alt-1"
                    id="ra-5"
                    name="rg-2"
                    value="ra5"
                />
                <Radio
                    labelText="Blue"
                    color="blue"
                    altStyle="alt-1"
                    id="ra-6"
                    name="rg-2"
                    value="ra6"
                />
                <Radio
                    labelText="Purple"
                    color="purple"
                    altStyle="alt-1"
                    id="ra-7"
                    name="rg-2"
                    value="ra7"
                />
                <h1 style={{ marginTop: '26px' }}>Alternative Radios 2</h1>
                <Radio
                    labelText="Primary"
                    altStyle="alt-2"
                    id="ra2-1"
                    name="rg-3"
                    value="ra21"
                />
                <Radio
                    labelText="Red"
                    color="red"
                    altStyle="alt-2"
                    id="ra2-2"
                    name="rg-3"
                    value="ra22"
                />
                <Radio
                    labelText="Orange"
                    color="orange"
                    altStyle="alt-2"
                    id="ra2-3"
                    name="rg-3"
                    value="ra23"
                />
                <Radio
                    labelText="Yellow"
                    color="yellow"
                    altStyle="alt-2"
                    id="ra2-4"
                    name="rg-3"
                    value="ra24"
                />
                <Radio
                    labelText="Green"
                    color="green"
                    altStyle="alt-2"
                    id="ra2-5"
                    name="rg-3"
                    value="ra25"
                />
                <Radio
                    labelText="Blue"
                    color="blue"
                    altStyle="alt-2"
                    id="ra2-6"
                    name="rg-3"
                    value="ra26"
                />
                <Radio
                    labelText="Purple"
                    color="purple"
                    altStyle="alt-2"
                    id="ra2-7"
                    name="rg-3"
                    value="ra27"
                />
                <h1 style={{ marginTop: '26px' }}>White-Only Radios</h1>
                <Radio
                    labelText="Primary"
                    id="wr-1"
                    name="rg-4"
                    value="wr1"
                    whiteOnly
                />
                <Radio
                    labelText="Red"
                    color="red"
                    id="wr-2"
                    name="rg-4"
                    value="wr2"
                    whiteOnly
                />
                <Radio
                    labelText="Orange"
                    color="orange"
                    id="wr-3"
                    name="rg-4"
                    value="wr3"
                    whiteOnly
                />
                <Radio
                    labelText="Yellow"
                    color="yellow"
                    id="wr-4"
                    name="rg-4"
                    value="wr4"
                    whiteOnly
                />
                <Radio
                    labelText="Green"
                    color="green"
                    id="wr-5"
                    name="rg-4"
                    value="wr5"
                    whiteOnly
                />
                <Radio
                    labelText="Blue"
                    color="blue"
                    id="wr-6"
                    name="rg-4"
                    value="wr6"
                    whiteOnly
                />
                <Radio
                    labelText="Purple"
                    color="purple"
                    id="wr-7"
                    name="rg-4"
                    value="wr7"
                    whiteOnly
                />
                <h1 style={{ marginTop: '26px' }}>Disabled Radios</h1>
                <Radio
                    labelText="Primary"
                    id="dr-1"
                    name="drg-1"
                    value="dr1"
                    disabled
                />
                <Radio
                    labelText="Red"
                    color="red"
                    id="dr-2"
                    name="drg-1"
                    value="dr2"
                    disabled
                />
                <Radio
                    labelText="Orange"
                    color="orange"
                    id="dr-3"
                    name="drg-1"
                    value="dr3"
                    disabled
                />
                <Radio
                    labelText="Yellow"
                    color="yellow"
                    id="dr-4"
                    name="drg-1"
                    value="dr4"
                    disabled
                />
                <Radio
                    labelText="Green"
                    color="green"
                    id="dr-5"
                    name="drg-1"
                    value="dr5"
                    disabled
                />
                <Radio
                    labelText="Blue"
                    color="blue"
                    id="dr-6"
                    name="drg-1"
                    value="dr6"
                    disabled
                />
                <Radio
                    labelText="Purple"
                    color="purple"
                    id="dr-7"
                    name="drg-1"
                    value="dr7"
                    disabled
                />
                <br />
                <Radio
                    labelText="Primary"
                    altStyle="alt-1"
                    id="dra-1"
                    name="drg-2"
                    value="dra1"
                    disabled
                />
                <Radio
                    labelText="Red"
                    color="red"
                    altStyle="alt-1"
                    id="dra-2"
                    name="drg-2"
                    value="dra2"
                    disabled
                />
                <Radio
                    labelText="Orange"
                    color="orange"
                    altStyle="alt-1"
                    id="dra-3"
                    name="drg-2"
                    value="dra3"
                    disabled
                />
                <Radio
                    labelText="Yellow"
                    color="yellow"
                    altStyle="alt-1"
                    id="dra-4"
                    name="drg-2"
                    value="dra4"
                    disabled
                />
                <Radio
                    labelText="Green"
                    color="green"
                    altStyle="alt-1"
                    id="dra-5"
                    name="drg-2"
                    value="dra5"
                    disabled
                />
                <Radio
                    labelText="Blue"
                    color="blue"
                    altStyle="alt-1"
                    id="dra-6"
                    name="drg-2"
                    value="dra6"
                    disabled
                />
                <Radio
                    labelText="Purple"
                    color="purple"
                    altStyle="alt-1"
                    id="dra-7"
                    name="drg-2"
                    value="dra7"
                    disabled
                />
                <br />
                <Radio
                    labelText="Primary"
                    altStyle="alt-2"
                    id="dra2-1"
                    name="drg-3"
                    value="dra21"
                    disabled
                />
                <Radio
                    labelText="Red"
                    color="red"
                    altStyle="alt-2"
                    id="dra2-2"
                    name="drg-3"
                    value="dra22"
                    disabled
                />
                <Radio
                    labelText="Orange"
                    color="orange"
                    altStyle="alt-2"
                    id="dra2-3"
                    name="drg-3"
                    value="dra23"
                    disabled
                />
                <Radio
                    labelText="Yellow"
                    color="yellow"
                    altStyle="alt-2"
                    id="dra2-4"
                    name="drg-3"
                    value="dra24"
                    disabled
                />
                <Radio
                    labelText="Green"
                    color="green"
                    altStyle="alt-2"
                    id="dra2-5"
                    name="drg-3"
                    value="dra25"
                    disabled
                />
                <Radio
                    labelText="Blue"
                    color="blue"
                    altStyle="alt-2"
                    id="dra2-6"
                    name="drg-3"
                    value="dra26"
                    disabled
                />
                <Radio
                    labelText="Purple"
                    color="purple"
                    altStyle="alt-2"
                    id="dra2-7"
                    name="drg-3"
                    value="dra27"
                    disabled
                />
                <br />
                <Radio
                    labelText="Primary"
                    id="dwr-1"
                    name="drg-4"
                    value="dwr1"
                    whiteOnly
                    disabled
                />
                <Radio
                    labelText="Red"
                    color="red"
                    id="dwr-2"
                    name="drg-4"
                    value="dwr2"
                    whiteOnly
                    disabled
                />
                <Radio
                    labelText="Orange"
                    color="orange"
                    id="dwr-3"
                    name="drg-4"
                    value="dwr3"
                    whiteOnly
                    disabled
                />
                <Radio
                    labelText="Yellow"
                    color="yellow"
                    id="dwr-4"
                    name="drg-4"
                    value="dwr4"
                    whiteOnly
                    disabled
                />
                <Radio
                    labelText="Green"
                    color="green"
                    id="dwr-5"
                    name="drg-4"
                    value="dwr5"
                    whiteOnly
                    disabled
                />
                <Radio
                    labelText="Blue"
                    color="blue"
                    id="dwr-6"
                    name="drg-4"
                    value="dwr6"
                    whiteOnly
                    disabled
                />
                <Radio
                    labelText="Purple"
                    color="purple"
                    id="dwr-7"
                    name="drg-4"
                    value="dwr7"
                    whiteOnly
                    disabled
                />
                <h1 style={{ marginTop: '26px' }}>Sized Radios</h1>
                <Radio
                    labelText="Small"
                    id="sr-small"
                    size="small"
                    name="srg"
                    value="srsmall"
                />
                <Radio
                    labelText="Default"
                    id="sr-default"
                    name="srg"
                    value="srdefault"
                />
                <Radio
                    labelText="Large"
                    id="sr-large"
                    size="large"
                    name="srg"
                    value="srlarge"
                />
            </div>
        </FlexibleSection>
    );
}

export default RadioSampleSection;
